export const vaccineCodes = () => {
  return {
    "10517": "BCG",
    "29659": "HPV",
    "24014": "Measles - Rubella",
    "3573": "Pneumococcal",
    "2763": "Rotavirus",
    "2748": "Rubella",
    "1002": "Yellow Fever",
    "3549": "Inactivated Polio",
    "54379": "Bivalent Polio",
    "54377":"Oral Polio",
    "15846": "Malaria",
    "1107": "Vitamin A",
    "50732": "Tdap",
    "18035": "Tdap",
    "13809": "Rabies",
    "6306": "Influenza",
    "16927": "Covid 19 Astrazeneca", //Astrazeneca
    "16929": "Covid 19 Pfizer-BioNtech", // Pfizer-BioNtech
    "16931": "Covid 19 Moderna", // Moderna
    "16489": "Covid 19 Sinopharm", //Sinopharm
    "16537" :"Covid 19 Johnson & Johnson'",// Johnson
    "11742":"Albendazole",
    "14676": "Tetanus" // 
  };

  
};

export const nonRoutineVaccince = () => {
  return {
    "16927": "Covid 19 Astrazeneca",
    "16931": "Covid 19 Moderna",
    "16489": "Covid 19 Sinopharm",
    "16929": "Covid 19 Pfizer-BioNTech",
    "16537": "Covid 19 Johnson",
    "14676": "Tetanus",
    "1002": "Yellow Fever",
    "13809": "Rabies Post Exposure",
    "6306": "Influenza", 
  };
};
export const routineRefinedVaccines = [
  {
    vaccineName: 'BCG',
    vaccineCode: 'IMBCG-I',
    nhddCode: '10517',
    diseaseTarget: 'Tuberculosis',
    doseNumber: '1', 
  },
  {
    vaccineName: 'bOPV',
    vaccineCode: 'IMPO-bOPV',
    nhddCode: '54379',
    diseaseTarget: 'Polio',
    doseNumber: '0', 
  },
  {
    vaccineName: 'OPV I',
    vaccineCode: 'IMPO-OPV-I',
    nhddCode: '54377',
    diseaseTarget: 'Polio',
    doseNumber: '1', 
  },
  {
    vaccineName: 'DPT-HepB+Hib 1',
    vaccineCode: 'IMDPT-1',
    nhddCode: '50732',
    diseaseTarget: 'DPT-HepB+Hib 1',
    doseNumber: '1', 
  },
  {
    vaccineName: 'PCV10 1',
    vaccineCode: 'IMPCV10-1',
    nhddCode: '3573',
    diseaseTarget: 'Pneumonia',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Rotavirus 1',
    vaccineCode: 'IMROTA-1',
    nhddCode: '2763',
    diseaseTarget: 'Rotavirus',
    doseNumber: '1', 
  },
  {
    vaccineName: 'OPV II',
    vaccineCode: 'IMPO-OPV-II',
    nhddCode: '54377',
    diseaseTarget: 'Polio',
    doseNumber: '2', 
  },
  {
    vaccineName: 'DPT-HepB+Hib 2',
    vaccineCode: 'IMDPT-2',
    nhddCode: '18035',
    diseaseTarget:
      'Diptheria, Pertussis, Tetanus, Hepatitis B, Influenza type B',
    doseNumber: '2', 
  },
  {
    vaccineName: 'PCV10 2',
    vaccineCode: 'IMPCV10-2',
    nhddCode: '3573',
    diseaseTarget: 'Pneumonia',
    doseNumber: '2', 
  },
  {
    vaccineName: 'Rotavirus 2',
    vaccineCode: 'IMROTA-2',
    nhddCode: '2763',
    diseaseTarget: 'Rotavirus',
    doseNumber: '2', 
  },
  {
    vaccineName: 'OPV III',
    vaccineCode: 'IMPO-OPV-III',
    nhddCode: '54377',
    diseaseTarget: 'Polio',
    doseNumber: '3', 
  },
  {
    vaccineName: 'DPT-HepB+Hib 3',
    vaccineCode: 'IMDPT-3',
    nhddCode: '50732',
    diseaseTarget:
      'Diptheria, Pertussis, Tetanus, Hepatitis B, Influenza type B',
    doseNumber: '3', 
  },
  {
    vaccineName: 'PCV10 3',
    vaccineCode: 'IMPCV10-3',
    nhddCode: '3573',
    diseaseTarget: 'Pneumonia',
    doseNumber: '3', 
  },
  {
    vaccineName: 'IPV',
    vaccineCode: 'IMPO-IPV I',
    nhddCode: '3549',
    diseaseTarget: 'Polio',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Rotavirus 3',
    vaccineCode: 'IMROTA-3',
    nhddCode: '2763',
    diseaseTarget: 'Rotavirus',
    doseNumber: '3', 
  },
  {
    vaccineName: 'Vitamin A 1st Dose',
    vaccineCode: 'IMVIT-1',
    nhddCode: '1107',
    diseaseTarget: 'Vitamin A Deficiency',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Measles-Rubella',
    vaccineCode: 'IMMEAS-0',
    nhddCode: '24014',
    diseaseTarget: 'Measles, Rubella',
    doseNumber: '1', 
  },
  {
    vaccineName: 'RTS/AS01 (Malaria Vaccine - 1)',
    vaccineCode: 'IMMALA-1',
    nhddCode: '15846',
    diseaseTarget: 'Malaria',
    doseNumber: '1', 
  },
  {
    vaccineName: 'RTS/AS01 (Malaria Vaccine - 2)',
    vaccineCode: 'IMMALA-2',
    nhddCode: '15846',
    diseaseTarget: 'Malaria',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Measles-Rubella 1st Dose',
    vaccineCode: 'IMMEAS-1',
    nhddCode: '24014',
    diseaseTarget: 'Measles, Rubella',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Yellow Fever',
    vaccineCode: 'IMYF-I',
    nhddCode: '1002',
    diseaseTarget: 'Yellow Fever',
    doseNumber: '1', 
  },
  {
    vaccineName: 'RTS/AS01 (Malaria Vaccine - 3)',
    vaccineCode: 'IMMALA-3',
    nhddCode: '15846',
    diseaseTarget: 'Malaria',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Vitamin A 2nd Dose',
    vaccineCode: 'IMVIT-2',
    nhddCode: '1107',
    diseaseTarget: 'Vitamin A Deficiency',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Albendazole 1st Dose',
    vaccineCode: 'IMALB-1',
    nhddCode: '11742',
    diseaseTarget: 'Worms',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Albendazole 2nd Dose',
    vaccineCode: 'IMALB-2',
    nhddCode: '11742',
    diseaseTarget: 'Worms',
    doseNumber: '2', 
  },
  {
    vaccineName: 'Albendazole 3rd Dose',
    vaccineCode: 'IMALB-3',
    nhddCode: '11742',
    diseaseTarget: 'Worms',
    doseNumber: '3', 
  },

  {
    vaccineName: 'Albendazole 4th Dose',
    vaccineCode: 'IMALB-4',
    nhddCode: '11742',
    diseaseTarget: 'Worms',
    doseNumber: '4', 
  },
  {
    vaccineName: 'Albendazole 5th Dose',
    vaccineCode: 'IMALB-5',
    nhddCode: '11742',
    diseaseTarget: 'Worms',
    doseNumber: '5', 
  },
  {
    vaccineName: 'Albendazole 6th Dose',
    vaccineCode: 'IMALB-6',
    nhddCode: '11742',
    diseaseTarget: 'Worms',
    doseNumber: '6', 
  },
  {
    vaccineName: 'Albendazole 7th Dose',
    vaccineCode: 'IMALB-7',
    nhddCode: '11742',
    diseaseTarget: 'Worms',
    doseNumber: '7', 
  },
  {
    vaccineName: 'Albendazole 8th Dose',
    vaccineCode: 'IMALB-8',
    nhddCode: '11742',
    diseaseTarget: 'Worms',
    doseNumber: '8', 
  },
  {
    vaccineName: 'Albendazole 9th Dose',
    vaccineCode: 'IMALB-9',
    nhddCode: '11742',
    diseaseTarget: 'Worms',
    doseNumber: '9', 
  },
  {
    vaccineName: 'Measles-Rubella 2nd Dose',
    vaccineCode: 'IMMEAS-2',
    nhddCode: '24014',
    diseaseTarget: 'Measles, Rubella',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Vitamin A 3rd Dose',
    vaccineCode: 'IMVIT-3',
    nhddCode: '1107',
    diseaseTarget: 'Vitamin A Deficiency',
    doseNumber: '1', 
  },
  {
    vaccineName: 'RTS/AS01 (Malaria Vaccine - 4)',
    vaccineCode: 'IMMALA-4',
    nhddCode: '15846',
    diseaseTarget: 'Malaria',
    doseNumber: '1', 
  },
]

export const nonRoutineRefinedVaccines = [
  {
    vaccineName: 'HPV Vaccine 1',
    vaccineCode: 'IMHPV-1',
    nhddCode: '29659',
    diseaseTarget: 'Human Papillomavirus',
    doseNumber: '1', 
  },
  {
    vaccineName: 'HPV Vaccine 2',
    vaccineCode: 'IMHPV-2',
    nhddCode: '29659',
    diseaseTarget: 'Human Papillomarivus',
    doseNumber: '2', 
  },
  {
    vaccineName: 'AstraZeneca',
    vaccineCode: 'IMCOV-ASTR-1',
    nhddCode: '16927',
    diseaseTarget: 'Covid 19 (SARS-CoV-2)',
    doseNumber: '1', 
  },
  {
    vaccineName: 'AstraZeneca 2nd Dose',
    vaccineCode: 'IMCOV-ASTR-2',
    nhddCode: '16927',
    diseaseTarget: 'Covid 19 (SARS-CoV-2)',
    doseNumber: '2', 
  },
  {
    vaccineName: 'Johnson & Johnson',
    vaccineCode: 'IMCOV-JnJ-0',
    nhddCode: '16927',
    diseaseTarget: 'Covid 19 (SARS-CoV-2)',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Pfizer/BioNTech 1st Dose',
    vaccineCode: 'IMCOV-PFIZER-1',
    nhddCode: '16929',
    diseaseTarget: 'Covid 19 (SARS-CoV-2)',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Pfizer/BioNTech 2nd Dose',
    vaccineCode: 'IMCOV-PFIZER-2',
    nhddCode: '16929',
    diseaseTarget: 'Covid 19 (SARS-CoV-2)',
    doseNumber: '2', 
  },
  {
    vaccineName: 'Moderna 1st Dose',
    vaccineCode: 'IMCOV-MOD-1',
    nhddCode: '16931',
    diseaseTarget: 'Covid 19 (SARS-CoV-2)',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Moderna 2nd Dose',
    vaccineCode: 'IMCOV-MOD-2',
    nhddCode: '16931',
    diseaseTarget: 'Covid 19 (SARS-CoV-2)',
    doseNumber: '2', 
  },
  {
    vaccineName: 'Sinopharm 1st Dose',
    vaccineCode: 'IMCOV-SINO-1',
    nhddCode: '16489',
    diseaseTarget: 'Covid 19 (SARS-CoV-2)',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Sinopharm 2nd Dose',
    vaccineCode: 'IMCOV-SINO-2',
    nhddCode: '16489',
    diseaseTarget: 'Covid 19 (SARS-CoV-2)',
    doseNumber: '2', 
  },
  {
    vaccineName: 'Tetanus 1',
    vaccineCode: 'IMTD-1',
    nhddCode: '50732',
    diseaseTarget: 'Tetanus',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Tetanus 2',
    vaccineCode: 'IMTD-2',
    nhddCode: '50732',
    diseaseTarget: 'Tetanus',
    doseNumber: '2', 
  },
  {
    vaccineName: 'Tetanus 3',
    vaccineCode: 'IMTD-3',
    nhddCode: '50732',
    diseaseTarget: 'Tetanus',
    doseNumber: '3', 
  },
  {
    vaccineName: 'Tetanus 4',
    vaccineCode: 'IMTD-4',
    nhddCode: '50732',
    diseaseTarget: 'Tetanus',
    doseNumber: '4', 
  },
  {
    vaccineName: 'Tetanus 5',
    vaccineCode: 'IMTD-5',
    nhddCode: '50732',
    diseaseTarget: 'Tetanus',
    doseNumber: '5', 
  },
  // {
  //   vaccineName: 'Yellow Fever',
  //   vaccineCode: 'IMYF-I',
  //   nhddCode: '1002',
  //   diseaseTarget: 'Yellow Fever',
  //   doseNumber: '1', 
  // },

  {
    vaccineName: 'Rabies 1',
    vaccineCode: 'IMRABIES-RABIES-1',
    nhddCode: '13809',
    diseaseTarget: 'Rabies',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Rabies 2',
    vaccineCode: 'IMRABIES-RABIES-2',
    nhddCode: '13809',
    diseaseTarget: 'Rabies',
    doseNumber: '2', 
  },
  {
    vaccineName: 'Rabies 3',
    vaccineCode: 'IMRABIES-RABIES-3',
    nhddCode: '13809',
    diseaseTarget: 'Rabies',
    doseNumber: '3', 
  },
  {
    vaccineName: 'Rabies 4',
    vaccineCode: 'IMRABIES-RABIES-4',
    nhddCode: '13809',
    diseaseTarget: 'Rabies',
    doseNumber: '4', 
  },
  {
    vaccineName: 'Rabies 5',
    vaccineCode: 'IMRABIES-RABIES-5',
    nhddCode: '13809',
    diseaseTarget: 'Rabies',
    doseNumber: '5', 
  },
  {
    vaccineName: 'Influenza 1',
    vaccineCode: 'IMINFLU-1',
    nhddCode: '6306',
    diseaseTarget: 'Influenza',
    doseNumber: '1', 
  },
  {
    vaccineName: 'Influenza 2',
    vaccineCode: 'IMINFLU-2',
    nhddCode: '6306',
    diseaseTarget: 'Influenza',
    doseNumber: '2', 
  },
]