# version: "3"
networks:
    openhim:
    hapi-fhir:
    cloudbuild: 
        external: true

services:
    mongo:
        container_name: openhim-mongo
        image: mongo:4.0
        networks:
            - openhim
        volumes:
            - mongodb-data:/data/db
        restart: unless-stopped

    hapi-fhir-postgres:
        container_name: hapi-fhir-postgres
        image: postgres:14-alpine
        restart: always
        networks:
            - hapi-fhir
            - cloudbuild
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: hapi
            POSTGRES_PASSWORD: hapi123
        volumes:
            - 'hapi-fhir-postgres:/var/lib/postgresql/data'

    hapi-fhir-jpa:
        image: hapiproject/hapi:v6.8.0
        container_name: hapi-fhir-jpa
        restart: unless-stopped
        networks:
            - hapi-fhir
            - cloudbuild
        depends_on:
            - hapi-fhir-postgres
        # ports:
        #      - "8081:8080"
        volumes:
            - "./hapi-fhir:/hapi"
        environment:
            SPRING_CONFIG_LOCATION: /hapi/application.yaml

    openhim-core:
        container_name: openhim-core
        restart: unless-stopped
        image: jembi/openhim-core:latest
        env_file:
            - .env
        ports:
            - "8080:8080"
            # - "5000:5000"
            - "5001:5001"
        depends_on:
            - mongo
        networks:
            - openhim
            - hapi-fhir
            - cloudbuild
        healthcheck:
            test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
            interval: 30s
            timeout: 30s
            retries: 3

    openhim-console:
        container_name: openhim-console
        image: jembi/openhim-console:latest
        restart: unless-stopped
        networks:
            - openhim
            - cloudbuild
        healthcheck:
            test: "curl -sS http://openhim-console || exit 1"
            interval: 30s
            timeout: 30s
            retries: 3
        volumes:
            - ./default.json:/usr/share/nginx/html/config/default.json:ro
            - /etc/ssl/crt:/etc/nginx/certs
    
    authservice:
        container_name: authservice
        build: 
            context: ../authservice
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - cloudbuild
            - hapi-fhir
        env_file:
            - ../authservice/.env
            
    hapi-fhir-config:
        depends_on:
            - hapi-fhir-jpa
        container_name: hapi-fhir-config
        networks:
            - cloudbuild
        build: 
            context: ../hapi-fhir-config
            dockerfile: Dockerfile

volumes:
    mongodb-data:
    hapi-fhir-postgres:
    hapi:
