volumes:
  keycloak-postgres:
      driver: local

networks:
  cloudbuild:
    # driver: overlay
    external: true
    

services:
  keycloak-postgres:
      image: postgres:14-alpine
      restart: on-failure
      networks:
            - cloudbuild
      environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: keycloak
          POSTGRES_PASSWORD: keycloak_not_123
      volumes:
        - 'keycloak-postgres:/var/lib/postgresql/data'

  keycloak:
      image: quay.io/keycloak/keycloak:26.0.1
      restart: on-failure
      networks:
        - cloudbuild
      env_file:
        - ../keycloak/.env
      depends_on:
        - keycloak-postgres
      command: start-dev --db=postgres --db-url=jdbc:postgresql://keycloak-postgres:5432/keycloak
      ports:
        - 8082:8080